import React from "react";
import TestRenderer, { act } from "react-test-renderer";
import { describe, expect, it, vi } from "vitest";

const save = vi.hoisted(() => vi.fn());
vi.mock("@/components/ui/button", () => ({ Button: ({ children, ...props }: any) => React.createElement("button", props, children) }));
vi.mock("@/components/ui/card", () => ({ Card: ({ children }: any) => React.createElement("div", {}, children), CardContent: ({ children }: any) => React.createElement("div", {}, children) }));
vi.mock("@/components/ui/input", () => ({ Input: (props: any) => React.createElement("input", props) }));
vi.mock("@/components/ui/label", () => ({ Label: ({ children, ...props }: any) => React.createElement("label", props, children) }));
vi.mock("@/components/DashboardLayout", () => ({ default: ({ children }: any) => React.createElement("div", {}, children) }));
vi.mock("@/components/PageHeader", () => ({ PageHeader: ({ title, action }: any) => React.createElement("header", {}, title, action) }));
vi.mock("@/_core/hooks/useAuth", () => ({ useAuth: () => ({ user: { role: "Administrateur" } }) }));
vi.mock("@/contexts/TenantContext", () => ({ useTenant: () => ({ tenantId: "tenant-a", tenants: [{ tenant: { id: "tenant-a" }, membership: { role: "Administrateur" } }] }) }));
vi.mock("@/contexts/I18nContext", () => ({ useI18n: () => ({ t: (key: string, values: Record<string, string | number> = {}) => ({ "selectionTypes.new": "New type", "selectionTypes.title": "Hierarchical selections", "selectionTypes.addNode": "Add element", "selectionTypes.loadExample": "Load Region → Prefecture → Commune example", "selectionTypes.previewTitle": "Tree preview", "selectionTypes.previewDescription": "Visually verify parent-child links before saving.", "selectionTypes.previewEmpty": "Add elements to display the tree.", "selectionTypes.emptyNode": "Unnamed element", "selectionTypes.orphanWarning": "{count} element(s) have a missing parent.", "selectionTypes.save": "Save type", "selectionTypes.name": "Name", "selectionTypes.key": "Key", "selectionTypes.levelLabel": "Level", "selectionTypes.nodeLabel": "Displayed label", "selectionTypes.nodeValue": "Stored value", "selectionTypes.nodeLevel": "Level", "selectionTypes.nodeParent": "Direct parent", "selectionTypes.root": "Root", "selectionTypes.created": "Created", "selectionTypes.empty": "Empty", "selectionTypes.emptyDescription": "Empty description", "selectionTypes.eyebrow": "Types", "selectionTypes.description": "Description", "selectionTypes.cancel": "Cancel", "selectionTypes.levels": "Levels", "selectionTypes.nodes": "Nodes", "selectionTypes.nodeGuide": "Add one row per element. Choose its level, then its direct parent from the preceding level. Elements in the first level are roots.", "selectionTypes.invalid": "Invalid", "selectionTypes.addLevel": "Add level", "selectionTypes.delete": "Delete", "selectionTypes.edit": "Edit", "selectionTypes.deleteConfirm": "Delete?", "selectionTypes.nodeCount": `${values.count ?? 0} elements`, "selectionTypes.selectTenant": "Select tenant", "selectionTypes.updated": "Updated", "selectionTypes.deleted": "Deleted", "selectionTypes.keyHint": "geo", "common.loading": "Loading" } as Record<string, string>)[key] ?? key }) }));
vi.mock("@/lib/trpc", () => ({ trpc: { useUtils: () => ({ biocollect: { selectionTypes: { list: { invalidate: vi.fn() } } } }), biocollect: { selectionTypes: { list: { useQuery: () => ({ data: [], isLoading: false }) }, create: { useMutation: () => ({ mutate: save, isPending: false }) }, update: { useMutation: () => ({ mutate: vi.fn(), isPending: false }) }, delete: { useMutation: () => ({ mutate: vi.fn() }) } } } } }));
vi.mock("lucide-react", () => ({ GitBranch: () => null, Loader2: () => null, Network: () => null, Plus: () => null, Trash2: () => null }));
vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: vi.fn() } }));

import SelectionTypes from "../../web/src/pages/SelectionTypes";
import { fr } from "../../../packages/i18n/src/locales/fr.ts";
import { en } from "../../../packages/i18n/src/locales/en.ts";

describe("page Types hiérarchiques", () => {
  it("prépare deux niveaux et crée un type avec son premier nœud", async () => {
    let renderer!: TestRenderer.ReactTestRenderer; save.mockClear(); await act(async () => { renderer = TestRenderer.create(React.createElement(SelectionTypes)); });
    const button = (label: string) => renderer.root.findAllByType("button" as any).find(item => String(item.props.children).includes(label));
    await act(async () => { button("New type")?.props.onClick(); });
    const inputs = renderer.root.findAllByType("input" as any); expect(inputs.filter(item => item.props.placeholder === "Level")).toHaveLength(2); expect(JSON.stringify(renderer.toJSON())).toContain("Add one row per element");
    await act(async () => { renderer.root.findByProps({ id: "selection-type-name" }).props.onChange({ target: { value: "Geolocation" } }); renderer.root.findByProps({ id: "selection-type-key" }).props.onChange({ target: { value: "geolocation" } }); inputs.filter(item => item.props.placeholder === "Level")[0].props.onChange({ target: { value: "Region" } }); inputs.filter(item => item.props.placeholder === "Level")[1].props.onChange({ target: { value: "Prefecture" } }); });
    await act(async () => { button("Add element")?.props.onClick(); });
    expect(renderer.root.findAllByType("input" as any).filter(item => item.props["aria-label"] === "Displayed label")).toHaveLength(1); expect(renderer.root.findAllByType("input" as any).filter(item => item.props["aria-label"] === "Stored value")).toHaveLength(1); expect(renderer.root.findAllByType("select" as any).filter(item => item.props["aria-label"] === "Level")).toHaveLength(1); expect(renderer.root.findAllByType("select" as any).filter(item => item.props["aria-label"] === "Direct parent")).toHaveLength(1);
    const nodeLabel = renderer.root.findAllByType("input" as any).find(item => item.props.placeholder === "Displayed label"); await act(async () => { nodeLabel?.props.onChange({ target: { value: "Maritime" } }); });
    await act(async () => { button("Save type")?.props.onClick(); });
    expect(save).toHaveBeenCalled(); const created = save.mock.calls[0][0]; expect(created).toMatchObject({ tenantId: "tenant-a", key: "geolocation", name: "Geolocation" }); expect(created.levels.map((level: any) => ({ label: level.label, order: level.order }))).toEqual([{ label: "Region", order: 0 }, { label: "Prefecture", order: 1 }]); expect(created.nodes).toEqual(expect.arrayContaining([expect.objectContaining({ label: "Maritime", value: "Maritime" })]));
  });

  it("expose les libellés bilingues du modèle et de la prévisualisation", () => { expect(fr.selectionTypes.loadExample).toContain("Région → Préfecture → Commune"); expect(fr.selectionTypes.previewTitle).toBe("Prévisualisation de l’arborescence"); expect(fr.selectionTypes.previewDescription).toContain("parent-enfant"); expect(fr.selectionTypes.previewEmpty).toContain("Ajoutez des éléments"); expect(fr.selectionTypes.orphanWarning).toContain("{count}"); expect(en.selectionTypes.loadExample).toContain("Region → Prefecture → Commune"); expect(en.selectionTypes.previewTitle).toBe("Tree preview"); expect(en.selectionTypes.previewDescription).toContain("parent-child"); expect(en.selectionTypes.previewEmpty).toContain("Add elements"); expect(en.selectionTypes.orphanWarning).toContain("{count}"); });

  it("charge l’exemple Région → Préfecture → Commune et affiche ses relations", async () => { let renderer!: TestRenderer.ReactTestRenderer; await act(async () => { renderer = TestRenderer.create(React.createElement(SelectionTypes)); }); const button = (label: string) => renderer.root.findAllByType("button" as any).find(item => String(item.props.children).includes(label)); await act(async () => { button("New type")?.props.onClick(); }); await act(async () => { button("Load Region")?.props.onClick(); }); expect(renderer.root.findByProps({ id: "selection-type-name" }).props.value).toBe("Géolocalisation administrative"); expect(renderer.root.findByProps({ id: "selection-type-key" }).props.value).toBe("geolocalisation"); expect(renderer.root.findAllByProps({ role: "tree" })).toHaveLength(1); expect(JSON.stringify(renderer.toJSON())).toContain("Load Region → Prefecture → Commune example"); expect(JSON.stringify(renderer.toJSON())).toContain("Tree preview"); expect(JSON.stringify(renderer.toJSON())).toContain("Visually verify parent-child links before saving."); expect(JSON.stringify(renderer.toJSON())).toContain("Maritime"); expect(JSON.stringify(renderer.toJSON())).toContain("Golfe"); expect(JSON.stringify(renderer.toJSON())).toContain("Lomé"); });
});
