import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";

const state = vi.hoisted(() => ({ reference: null as { id: string } | null, submission: null as any, updates: [] as string[], resolveInput: null as any, tenantCreate: null as any, tenantSelection: null as any, tenantUpdate: null as any, configurationUpdate: null as any, referenceDataCreate: null as any, formCreate: null as any, draft: null as any, phoneDefaults: {} as any, tenantInvite: null as any }));

vi.mock("../_core/keycloakAdmin", () => ({
  isKeycloakAdminConfigured: vi.fn(() => true),
  inviteOrEnsureKeycloakUser: vi.fn(async ({ email }: { email: string }) => ({
    user: { id: "kc-admin-1", email, firstName: "Admin", lastName: "Test" },
    created: true,
    emailSent: true,
  })),
  resendKeycloakInviteEmail: vi.fn(),
}));

vi.mock("../tenantDb", () => ({
  requireTenantRole: vi.fn(async ({ tenantId }: { tenantId: string }) => tenantId === "tenant-a" ? { tenant: { id: "tenant-a", isActive: true }, role: "Administrateur" } : null),
  createTenant: vi.fn(async (input: any) => { state.tenantCreate = input; return { id: "tenant-new", name: input.name, slug: "nouvel-espace" }; }),
  selectActiveTenant: vi.fn(async (input: any) => { state.tenantSelection = input; return { id: input.tenantId }; }),
  updateTenantBySuperadmin: vi.fn(async (input: any) => { state.tenantUpdate = input; return { id: input.tenantId, ...input }; }),
  addTenantMember: vi.fn(async (input: any) => { state.tenantInvite = input; return "membership-1"; }),
  getTenantMember: vi.fn(async () => ({ userId: 99, role: "Administrateur" })),
  listUserTenants: vi.fn(async () => []), listAllTenants: vi.fn(async () => []), listTenantProjects: vi.fn(async () => []),
  createTenantProject: vi.fn(), getTenantProjectConfiguration: vi.fn(async (tenantId: string) => tenantId === "tenant-a" ? { project: { id: "project-1", isActive: true }, config: { requiredFingers: ["RIGHT_THUMB"], nfiqThreshold: 3, matchingThreshold: 85 } } : null),
  updateTenantProjectConfiguration: vi.fn(async (input: any) => { state.configurationUpdate = input; return { project: { id: input.projectId }, config: input }; }),
  listTenantForms: vi.fn(async () => []), createTenantForm: vi.fn(async (input: any) => { state.formCreate = input; return { id: "form-new", version: 1 }; }), listTenantFormDrafts: vi.fn(async () => state.draft ? [state.draft] : []), saveTenantFormDraft: vi.fn(async (input: any) => { state.draft = { id: input.draftId ?? "draft-new", ...input }; return state.draft; }), deleteTenantFormDraft: vi.fn(async (_tenantId: string, _projectId: string, draftId: string) => { if (!state.draft || state.draft.id !== draftId) return false; state.draft = null; return true; }), getTenantPhoneValidationDefaults: vi.fn(async () => state.phoneDefaults), updateTenantPhoneValidationDefaults: vi.fn(async (input: any) => { state.phoneDefaults = input.validation; return state.phoneDefaults; }), getTenantSyncBundle: vi.fn(), getTenantDashboard: vi.fn(async () => ({ summary: {}, evolution: [] })), listTenantConflictCases: vi.fn(async () => []),
  listTenantReferenceDataSets: vi.fn(async () => []), createTenantReferenceDataSet: vi.fn(async (input: any) => { state.referenceDataCreate = input; return { id: "reference-new", ...input }; }), updateTenantReferenceDataSet: vi.fn(), deleteTenantReferenceDataSet: vi.fn(),
  getTenantReferenceDataSet: vi.fn(async (tenantId: string, referenceDataSetId: string) => tenantId === "tenant-a" && referenceDataSetId === "dataset-1" ? { id: "dataset-1", tenantId, options: [{ value: "true", label: "Oui" }, { value: "false", label: "Non" }] } : null),
  tenantOwnsSubmission: vi.fn(async (tenantId: string, submissionId: string) => tenantId === "tenant-a" && submissionId !== "outside"), assertTenantProject: vi.fn(async () => true),
}));

vi.mock("../db", () => ({
  createSyncedSubmission: vi.fn(async (input: any) => { state.submission = { id: "submission-1", projectId: input.projectId, status: "SYNCED", attachments: input.attachments }; return state.submission; }),
  getSubmissionWithAttachments: vi.fn(async () => state.submission),
  updateSubmissionStatus: vi.fn(async (_id: string, status: string, patch?: Record<string, unknown>) => { state.updates.push(status); state.submission = { ...state.submission, status, ...patch }; return state.submission; }),
  findValidatedReference: vi.fn(async () => state.reference),
  resolveConflict: vi.fn(async (input: any) => { state.resolveInput = input; return { id: input.suspectedSubmissionId, status: "REJECTED" }; }),
  getUserByOpenId: vi.fn(async () => null),
  getUserByEmail: vi.fn(async () => ({ id: 99, openId: "kc-admin-1", email: "admin@nord.tg", name: "Admin Test", role: "Administrateur" })),
  upsertUser: vi.fn(async () => {}),
}));

import { appRouter } from "../routers";

function context(role: "Superadmin" | "Administrateur" | "Superviseur" | "Enquêteur"): TrpcContext { return { user: { id: 42, openId: "test-user", name: "Test", email: "test@example.com", loginMethod: "test", role, createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { protocol: "https", headers: {} } as TrpcContext["req"], res: {} as TrpcContext["res"] }; }
const validPush = { tenantId: "tenant-a", projectId: "project-1", data: { nom: "Ada" }, attachments: [{ fingerType: "RIGHT_THUMB", minioPath: "minio://biocollect/fingerprints/ada.wsq", nfiqScore: 2 }] };

describe("isolation multi-tenant tRPC", () => {
  beforeEach(() => { state.reference = null; state.submission = null; state.updates = []; state.resolveInput = null; state.tenantCreate = null; state.tenantSelection = null; state.tenantUpdate = null; state.configurationUpdate = null; state.referenceDataCreate = null; state.formCreate = null; state.draft = null; state.phoneDefaults = {}; state.tenantInvite = null; });
  it("synchronise un dossier dans un espace autorisé et déclenche VALIDATED", async () => { const result = await appRouter.createCaller(context("Enquêteur")).biocollect.sync.push(validPush); expect(result?.status).toBe("VALIDATED"); expect(state.updates).toEqual(["PROCESSING", "VALIDATED"]); });
  it("refuse toute synchronisation dans un tenant non autorisé", async () => { await expect(appRouter.createCaller(context("Enquêteur")).biocollect.sync.push({ ...validPush, tenantId: "tenant-b" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("produit SUSPECTED_DUPLICATE dans le tenant autorisé", async () => { state.reference = { id: "validated-previous" }; const result = await appRouter.createCaller(context("Enquêteur")).biocollect.sync.push({ ...validPush, attachments: [{ ...validPush.attachments[0], minioPath: "minio://biocollect/fingerprints/duplicate-ada.wsq" }] }); expect(result?.status).toBe("SUSPECTED_DUPLICATE"); expect(result?.matchedSubmissionId).toBe("validated-previous"); });
  it("autorise un Superadmin à créer un tenant depuis le back-office", async () => { const result = await appRouter.createCaller(context("Superadmin")).biocollect.tenants.createBySuperadmin({ name: "Entité Nord", adminEmail: "admin@nord.tg" }); expect(result.id).toBe("tenant-new"); expect(result.emailSent).toBe(true); expect(state.tenantCreate).toMatchObject({ name: "Entité Nord", userId: 42, addCreatorMembership: false }); expect(state.tenantInvite).toMatchObject({ tenantId: "tenant-new", role: "Administrateur" }); });
  it("permet à une personne authentifiée de créer puis sélectionner son espace", async () => { const caller = appRouter.createCaller(context("Enquêteur")); const created = await caller.biocollect.tenants.create({ name: "Collectif Sud" }); expect(created.id).toBe("tenant-new"); await caller.biocollect.tenants.select({ tenantId: "tenant-a" }); expect(state.tenantSelection).toMatchObject({ tenantId: "tenant-a", userId: 42 }); });
  it("refuse à un Administrateur de créer un tenant Superadmin", async () => { await expect(appRouter.createCaller(context("Administrateur")).biocollect.tenants.createBySuperadmin({ name: "Interdit" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("permet au Superadmin de modifier l’état d’un tenant", async () => { await appRouter.createCaller(context("Superadmin")).biocollect.tenants.updateBySuperadmin({ tenantId: "tenant-a", name: "Entité renommée", isActive: false }); expect(state.tenantUpdate).toMatchObject({ tenantId: "tenant-a", name: "Entité renommée", isActive: false }); });
  it("refuse la résolution d’un conflit qui traverse deux espaces", async () => { await expect(appRouter.createCaller(context("Superviseur")).biocollect.conflicts.resolve({ tenantId: "tenant-a", suspectedSubmissionId: "new-1", targetSubmissionId: "outside", action: "Forcer Faux Positif" })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("enregistre la configuration d’un projet uniquement dans le tenant actif", async () => { await appRouter.createCaller(context("Administrateur")).biocollect.projects.updateConfiguration({ tenantId: "tenant-a", projectId: "project-1", requiredFingers: ["RIGHT_THUMB", "LEFT_THUMB"], nfiqThreshold: 2, matchingThreshold: 91 }); expect(state.configurationUpdate).toMatchObject({ tenantId: "tenant-a", projectId: "project-1" }); });
  it("crée un référentiel manuel dans le tenant administré", async () => { await appRouter.createCaller(context("Administrateur")).biocollect.referenceData.create({ tenantId: "tenant-a", type: "civil_status", name: "Statut civil", options: [{ value: "single", label: "Célibataire" }] }); expect(state.referenceDataCreate).toMatchObject({ tenantId: "tenant-a", type: "civil_status", createdBy: 42, options: [{ value: "single", label: "Célibataire" }] }); });
  it("prévisualise les codes, libellés, colonnes et mapping avant tout import", async () => { const preview = await appRouter.createCaller(context("Administrateur")).biocollect.referenceData.preview({ tenantId: "tenant-a", fileName: "consent.csv", contentBase64: Buffer.from("code,label\ntrue,Oui\nfalse,Non\n").toString("base64") }); expect(preview).toEqual({ rowCount: 2, columns: ["code", "label"], mapping: { valueColumn: "code", labelColumn: "label", usesSingleColumn: false }, options: [{ value: "true", label: "Oui" }, { value: "false", label: "Non" }] }); });
  it("matérialise les options code/libellé d’un référentiel dans le formulaire publié", async () => { await appRouter.createCaller(context("Administrateur")).biocollect.forms.create({ tenantId: "tenant-a", projectId: "project-1", name: "Enrôlement", isPublished: true, fields: [{ id: "status", label: "Statut", type: "multiple choice", required: true, referenceDataSetId: "dataset-1" }] }); expect(state.formCreate.fields[0]).toMatchObject({ referenceDataSetId: "dataset-1", options: [{ value: "true", label: "Oui" }, { value: "false", label: "Non" }] }); });
  it("refuse l’association d’un référentiel absent ou extérieur au tenant", async () => { await expect(appRouter.createCaller(context("Administrateur")).biocollect.forms.create({ tenantId: "tenant-a", projectId: "project-1", name: "Enrôlement", isPublished: true, fields: [{ id: "status", label: "Statut", type: "multiple choice", required: true, referenceDataSetId: "dataset-outside" }] })).rejects.toMatchObject({ code: "BAD_REQUEST" }); });
  it("sauvegarde un brouillon incomplet sans le publier et le rend disponible à la reprise", async () => { const caller = appRouter.createCaller(context("Administrateur")); const draft = await caller.biocollect.forms.saveDraft({ tenantId: "tenant-a", projectId: "project-1", name: "Brouillon partiel", fields: [], steps: [] }); expect(draft.id).toBe("draft-new"); expect(state.draft).toMatchObject({ projectId: "project-1", name: "Brouillon partiel", fields: [] }); const listed = await caller.biocollect.forms.drafts({ tenantId: "tenant-a", projectId: "project-1" }); expect(listed).toHaveLength(1); });
  it("enregistre les règles Téléphone par défaut de l’espace", async () => { const caller = appRouter.createCaller(context("Administrateur")); await caller.biocollect.forms.updatePhoneDefaults({ tenantId: "tenant-a", validation: { minLength: 8, maxLength: 10, allowedPrefixes: ["228"] } }); expect(await caller.biocollect.forms.phoneDefaults({ tenantId: "tenant-a" })).toEqual({ minLength: 8, maxLength: 10, allowedPrefixes: ["228"] }); });
  it("refuse une expression régulière invalide lors de la publication", async () => { await expect(appRouter.createCaller(context("Administrateur")).biocollect.forms.create({ tenantId: "tenant-a", projectId: "project-1", name: "Enrôlement", isPublished: true, fields: [{ id: "code", label: "Code", type: "text", required: true, validation: { textFormat: "regex", regex: "[" } }] })).rejects.toMatchObject({ code: "BAD_REQUEST" }); });
  it("publie un champ Sexe avec OTHER par défaut et respecte sa désactivation", async () => { const caller = appRouter.createCaller(context("Administrateur")); await caller.biocollect.forms.create({ tenantId: "tenant-a", projectId: "project-1", name: "Sexe standard", isPublished: true, fields: [{ id: "sex", label: "Sexe", type: "sex", required: true }] }); expect(state.formCreate.fields[0]).toMatchObject({ type: "sex", sexUseOther: true }); await caller.biocollect.forms.create({ tenantId: "tenant-a", projectId: "project-1", name: "Sexe binaire", isPublished: true, fields: [{ id: "sex", label: "Sexe", type: "sex", required: true, sexUseOther: false }] }); expect(state.formCreate.fields[0]).toMatchObject({ type: "sex", sexUseOther: false }); });
});
