import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useI18n } from "@/contexts/I18nContext";
import { useTenant } from "@/contexts/TenantContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Database, FileSpreadsheet, History, Loader2, Pencil, Plus, Trash2, Upload } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import DashboardLayout from "../components/DashboardLayout";
import { PageHeader } from "../components/PageHeader";
import { ImportPreviewSummary } from "../components/reference-data/ImportPreviewSummary";
import { ManualOptionEditor, normalizeManualOptionRows, type ManualOptionRow } from "../components/reference-data/ManualOptionEditor";

type Option = { value: string; label: string };
type EditorMode = "manual" | "import";

function optionRows(options: unknown): ManualOptionRow[] { return !Array.isArray(options) || !options.length ? [{ label: "", value: "" }] : options.map(item => typeof item === "string" ? { label: item, value: item } : { label: String((item as Option).label), value: String((item as Option).value) }); }

function ReferenceDataContent() {
  const { t } = useI18n(); const { user } = useAuth(); const { tenantId, tenants } = useTenant();
  const membership = tenants.find(entry => entry.tenant.id === tenantId)?.membership;
  const canManage = user?.role === "Superadmin" || user?.role === "Administrateur" || membership?.role === "Administrateur";
  const utils = trpc.useUtils(); const list = trpc.biocollect.referenceData.list.useQuery({ tenantId: tenantId ?? "" }, { enabled: Boolean(tenantId) });
  const [open, setOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [historyId, setHistoryId] = useState<string | null>(null); const history = trpc.biocollect.referenceData.history.useQuery({ tenantId: tenantId ?? "", referenceDataSetId: historyId ?? "" }, { enabled: Boolean(tenantId && historyId) }); const usage = trpc.biocollect.referenceData.usage.useQuery({ tenantId: tenantId ?? "", referenceDataSetId: historyId ?? "" }, { enabled: Boolean(tenantId && historyId) }); const [type, setType] = useState(""); const [name, setName] = useState(""); const [mode, setMode] = useState<EditorMode>("manual"); const [manualRows, setManualRows] = useState<ManualOptionRow[]>([{ label: "", value: "" }]); const [file, setFile] = useState<{ fileName: string; mimeType: string; contentBase64: string } | null>(null); const [preview, setPreview] = useState<{ rowCount: number; columns: string[]; mapping: { valueColumn: string; labelColumn: string; usesSingleColumn: boolean }; options: Option[] } | null>(null);
  const options = useMemo(() => normalizeManualOptionRows(manualRows), [manualRows]);
  const invalidate = () => utils.biocollect.referenceData.list.invalidate({ tenantId: tenantId ?? "" });
  const reset = () => { setOpen(false); setEditingId(null); setType(""); setName(""); setMode("manual"); setManualRows([{ label: "", value: "" }]); setFile(null); setPreview(null); };
  const create = trpc.biocollect.referenceData.create.useMutation({ onSuccess: () => { void invalidate(); toast.success(t("referenceData.created")); reset(); }, onError: error => toast.error(error.message) });
  const update = trpc.biocollect.referenceData.update.useMutation({ onSuccess: () => { void invalidate(); toast.success(t("referenceData.updated")); reset(); }, onError: error => toast.error(error.message) });
  const previewFile = trpc.biocollect.referenceData.preview.useMutation({ onSuccess: setPreview, onError: error => { setPreview(null); toast.error(error.message || t("referenceData.importFailed")); } });
  const imported = trpc.biocollect.referenceData.import.useMutation({ onSuccess: () => { void invalidate(); toast.success(editingId ? t("referenceData.updated") : t("referenceData.created")); reset(); }, onError: error => toast.error(error.message) });
  const remove = trpc.biocollect.referenceData.delete.useMutation({ onSuccess: () => { void invalidate(); toast.success(t("referenceData.deleted")); }, onError: error => toast.error(error.message) });
  const pending = create.isPending || update.isPending || imported.isPending;
  function chooseFile(selected?: File) { if (!selected || !tenantId) return; if (selected.size > 5 * 1024 * 1024) return toast.error(t("referenceData.acceptedFiles")); const reader = new FileReader(); reader.onload = () => { const uploaded = { fileName: selected.name, mimeType: selected.type || "application/octet-stream", contentBase64: String(reader.result).split(",")[1] ?? "" }; setFile(uploaded); setPreview(null); previewFile.mutate({ tenantId, fileName: uploaded.fileName, contentBase64: uploaded.contentBase64 }); }; reader.onerror = () => toast.error(t("referenceData.importFailed")); reader.readAsDataURL(selected); }
  function edit(item: any) { setEditingId(item.id); setType(item.type); setName(item.name); setManualRows(optionRows(item.options)); setMode(item.sourceFileKey ? "import" : "manual"); setFile(null); setPreview(null); setOpen(true); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!tenantId) return toast.error(t("referenceData.selectTenant")); if (mode === "import") { if (!file || !preview) return toast.error(t("referenceDataPreview.required")); imported.mutate({ tenantId, referenceDataSetId: editingId ?? undefined, type, name, ...file }); return; } if (!options.length) return toast.error(t("referenceData.optionsHint")); const payload = { tenantId, type, name, options }; if (editingId) update.mutate({ ...payload, referenceDataSetId: editingId }); else create.mutate(payload); }

  return <><PageHeader eyebrow={t("referenceData.eyebrow")} title={t("referenceData.title")} description={t("referenceData.description")} action={canManage ? <Button onClick={() => { reset(); setOpen(true); }}><Plus className="mr-2 h-4 w-4" />{t("referenceData.new")}</Button> : undefined} />
    {open && mode === "import" && preview ? <Card className="bio-panel mb-5 border-sky-100"><CardContent className="p-5"><ImportPreviewSummary preview={preview} /></CardContent></Card> : null}
    {open && mode === "import" && preview ? <Card className="bio-panel mb-5 border-sky-100"><CardContent className="p-5"><div className="mb-3 flex items-start justify-between gap-3"><div><p className="bio-kicker">{t("referenceDataPreview.title")}</p><p className="mt-1 text-sm text-slate-500">{t("referenceDataPreview.description")}</p></div><Badge variant="outline">{t("referenceDataPreview.rows", { count: preview.rowCount })}</Badge></div><div className="overflow-hidden rounded-lg border border-slate-100"><div className="grid grid-cols-2 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500"><span>{t("referenceDataPreview.code")}</span><span>{t("referenceDataPreview.label")}</span></div>{preview.options.map(option => <div key={option.value} className="grid grid-cols-2 border-t border-slate-100 px-3 py-2 text-sm"><span className="font-mono text-slate-600">{option.value}</span><span className="text-slate-900">{option.label}</span></div>)}</div></CardContent></Card> : null}
    {!tenantId ? <Card className="bio-panel"><CardContent className="py-12 text-center text-sm text-slate-500">{t("referenceData.selectTenant")}</CardContent></Card> : null}
    {open ? <Card className="bio-panel mb-6"><CardContent className="p-6"><form onSubmit={submit} className="grid gap-5"><div className="flex items-start justify-between"><div><p className="bio-kicker">{editingId ? t("referenceData.update") : t("referenceData.new")}</p><h2 className="mt-2 text-xl font-bold">{name || t("referenceData.title")}</h2></div><Button type="button" variant="ghost" onClick={reset}>{t("referenceData.cancelEdit")}</Button></div><div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label htmlFor="reference-name">{t("referenceData.name")}</Label><Input id="reference-name" minLength={3} required value={name} onChange={event => setName(event.target.value)} /></div><div className="grid gap-2"><Label htmlFor="reference-type">{t("referenceData.type")}</Label><Input id="reference-type" className="font-mono" placeholder={t("referenceData.typeHint")} pattern="[a-z][a-z0-9_-]*" required value={type} onChange={event => setType(event.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, ""))} /></div></div><fieldset className="flex flex-wrap gap-2 rounded-xl border border-slate-100 bg-slate-50 p-4"><legend className="px-1 text-sm font-semibold">{t("referenceData.source")}</legend><Button type="button" size="sm" variant={mode === "manual" ? "default" : "outline"} onClick={() => setMode("manual")}>{t("referenceData.manual")}</Button><Button type="button" size="sm" variant={mode === "import" ? "default" : "outline"} onClick={() => setMode("import")}><Upload className="mr-1 h-4 w-4" />{t("referenceData.importFile")}</Button></fieldset>{mode === "manual" ? <ManualOptionEditor rows={manualRows} onChange={setManualRows} t={t} /> : <div className="grid gap-3 rounded-xl border border-dashed border-sky-200 bg-sky-50/50 p-4"><div className="flex items-center gap-3"><FileSpreadsheet className="h-5 w-5 text-sky-700" /><div><Label htmlFor="reference-file">{t("referenceData.file")}</Label><p className="text-xs text-slate-500">{t("referenceData.acceptedFiles")}</p></div></div><Input id="reference-file" type="file" accept=".txt,.csv,.xls,.xlsx" onChange={event => chooseFile(event.target.files?.[0])} />{file ? <Badge className="w-fit" variant="outline">{t("referenceData.importedFile", { file: file.fileName })}</Badge> : null}</div>}<div className="flex justify-end"><Button type="submit" disabled={pending}>{pending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}{mode === "import" ? t("referenceData.import") : editingId ? t("referenceData.update") : t("referenceData.create")}</Button></div></form></CardContent></Card> : null}
    {list.isLoading && tenantId ? <div className="flex h-48 items-center justify-center text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin" />{t("referenceData.loading")}</div> : null}{list.data?.length === 0 && tenantId ? <Card className="bio-panel border-dashed"><CardContent className="flex min-h-56 flex-col items-center justify-center text-center"><Database className="mb-4 h-7 w-7 text-sky-700" /><h2 className="font-bold">{t("referenceData.empty")}</h2><p className="mt-2 max-w-md text-sm text-slate-500">{t("referenceData.emptyDescription")}</p></CardContent></Card> : null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.data?.map(item => <Card key={item.id} className="bio-panel bio-interactive"><CardContent className="p-6"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="bio-kicker">{item.type}</p><h2 className="mt-2 truncate text-lg font-bold">{item.name}</h2><p className="mt-2 text-sm text-slate-500">{t("referenceData.optionCount", { count: item.sourceRowCount })} · {t("referenceData.currentVersion", { version: item.currentVersion ?? 1 })}</p></div><Database className="h-5 w-5 shrink-0 text-sky-700" /></div><div className="mt-4 flex flex-wrap gap-1">{(item.options as Option[]).slice(0, 3).map(option => <Badge key={option.value} variant="outline">{option.label}</Badge>)}</div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setHistoryId(item.id)}><History className="mr-1 h-4 w-4" />{t("referenceData.viewHistory")}</Button>{canManage ? <><Button size="sm" variant="ghost" onClick={() => edit(item)}><Pencil className="mr-1 h-4 w-4" />{t("referenceData.edit")}</Button><Button size="sm" variant="ghost" className="text-rose-700" onClick={() => window.confirm(t("referenceData.deleteConfirm")) && remove.mutate({ tenantId: tenantId!, referenceDataSetId: item.id })}><Trash2 className="mr-1 h-4 w-4" />{t("referenceData.delete")}</Button></> : null}</div></CardContent></Card>)}</div>
    {historyId ? <Card className="bio-panel mt-6"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="bio-kicker">{t("referenceData.history")}</p><h2 className="mt-2 text-lg font-bold">{list.data?.find(item => item.id === historyId)?.name}</h2></div><Button size="sm" variant="ghost" onClick={() => setHistoryId(null)}>{t("common.close")}</Button></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><section><h3 className="text-sm font-semibold">{t("referenceData.versions")}</h3><div className="mt-3 grid gap-2">{history.isLoading ? <p className="text-sm text-slate-500">{t("common.loading")}</p> : history.data?.map(version => <div key={version.id} className="flex justify-between rounded-xl border border-slate-100 bg-slate-50 px-3 py-2"><span>{t("referenceData.version", { version: version.version })}</span><span className="text-xs text-slate-500">{t("referenceData.optionCount", { count: version.sourceRowCount })}</span></div>)}</div></section><section><h3 className="text-sm font-semibold">{t("referenceData.usedBy")}</h3><div className="mt-3 grid gap-2">{usage.isLoading ? <p className="text-sm text-slate-500">{t("common.loading")}</p> : usage.data?.length ? usage.data.map(entry => <div key={`${entry.formId}-${entry.fieldId}`} className="rounded-xl border border-slate-100 bg-slate-50 px-3 py-2"><p className="font-medium">{entry.formName} · v{entry.formVersion}</p><p className="mt-1 text-xs text-slate-500">{entry.projectName} · {entry.fieldLabel} · {t("referenceData.version", { version: entry.referenceDataSetVersion ?? 1 })}</p></div>) : <p className="text-sm text-slate-500">{t("referenceData.noUsage")}</p>}</div></section></div></CardContent></Card> : null}
  </>;
}

export default function ReferenceData() { return <DashboardLayout><ReferenceDataContent /></DashboardLayout>; }
